### ISSUE TITLE
Lack of visual feedback for commands

### ISSUE THREAD

**Issue by Boruch-Baum** [bpanthi977/org-mpv-notes#12]
The following functions give no visual feedback in the minibuffer to
the new state that they create.

    org-mpv-notes-speed-{up,down}
    org-mpv-notes-toggle-fullscreen
    org-mpv-notes-save-screenshot

**Comment by bpanthi977** [comment]
I have added visual feedback for:
```
org-mpv-notes-speed-{up,down}
org-mpv-notes-toggle-fullscreen
```
Since `org-mpv-notes-save-screenshot` prompts the user for image caption title and adds an inline image in the buffer. I feel no extra feedback is needed. So I have left its implementation as it is.
