### ISSUE TITLE
Seek stepping doesn't seem to do anything

### ISSUE THREAD

**Issue by Boruch-Baum** [bpanthi977/org-mpv-notes#14]
I can't figure out what the following interactive functions are meant
to accomplish:

    org-mpv-notes-seek-halve-step
    org-mpv-notes-seek-double-step

**Comment by bpanthi977** [comment]
The functionality is now correctly implemented. 

`org-mpv-notes-seek-forward` skips/seeks forward in the video (and `org-mpv-notes-seek-backward` seeks backward). The amount by which it moves forward/backward is controlled by `org-mpv-notes-seek-step`. These two function increase/decrease the seek step size.
