### ISSUE TITLE
Don't fail to create note when mpv not open

### ISSUE THREAD

**Issue by Boruch-Baum** [bpanthi977/org-mpv-notes#15]
The current behavior is to fail with an error message asking the user
the open a file with mpv.el or empv.el, but org-mpv-notes could easier
just run function org-mpv-notes-open directly if that function were
(interactive "f") - refer to issue #13

**Comment by bpanthi977** [comment]
Currently the message asks user to use `org-mpv-notes-open` to open a media file or url.
I think the current behaviour to explicitly  ask user is fine.
