### ISSUE TITLE
void function empv

### ISSUE THREAD

**Issue by studentz** [bpanthi977/org-mpv-notes#22]
Emacs 29.1.90
Org Version: 9.7.11

Steps to reproduce the error:

- org-mpv-notes-open    -> File -> /paht/to/mpv/file
- org-mpv-notes-mode
- RET on the link

Below is the info from debugger. 
Mpv installed and working, as well as empv mode.

Please let me know if you need more information.

Thanks,

```
Debugger entered--Lisp error: (void-function empv)
  empv(nil)
  org-mpv-notes--active-backend(t)
  org-mpv-notes--open("~/Documents/videos/ImitationLearnin..." nil)
  org-link-open((link (:standard-properties [20495 nil nil nil 20563 0 nil nil nil nil nil nil nil nil #<buffer imitation.org> nil nil (paragraph (:standard-properties [20495 20495 20495 20564 20566 2 nil nil element t nil nil nil nil #<buffer imitation.org> nil nil (section ...)]))] :type "mpv" :type-explicit-p t :path "~/Documents/videos/ImitationLearnin..." :format bracket :raw-link "mpv:~/Documents/videos/ImitationLea..." :application nil :search-option nil)) nil)
  org-open-at-point(nil)
  funcall-interactively(org-open-at-point nil)
  #<subr org-return>(t)
  apply(#<subr org-return> t)
  org-return(t)
  org-return-indent()
  (if (org-in-src-block-p) (org-return) (org-return-indent))
  (lambda nil (interactive) (if (org-in-src-block-p) (org-return) (org-return-indent)))()
  funcall-interactively((lambda nil (interactive) (if (org-in-src-block-p) (org-return) (org-return-indent))))
  command-execute((lambda nil (interactive) (if (org-in-src-block-p) (org-return) (org-return-indent))))
```

**Comment by bpanthi977** [comment]
Thanks for raising the issue. 

#23  should fix it.

**Comment by studentz** [comment]
Yeah, it's working now!

The result of creating the link to the MP4 file uses a relative path ('~'), but it only works with an absolute path.
Is there a way to use a relative path instead of an absolute one?
Do I need to customize any variables from empv or another package?

Thanks for your help.

**Comment by bpanthi977** [comment]
It's surprising that I never tried relative path names. 
Turns out mpv program requires absolute path names. 

#24 should fix this. 

Thanks for finding this out!
