### ISSUE TITLE
org-mpv-notes-link-regex support for youtube file format

### ISSUE THREAD

**Issue by Boruch-Baum** [bpanthi977/org-mpv-notes#9]
The regex currently doesn't support square bracket characters in file
names, which is part of the standard youtube file naming format. For
example, file

   How To Tie Your Shoes Insanely Fast! [6cBtqhq5P28].mp4

fails not because of the exclamation point, but because of the square
brackets.

**Comment by bpanthi977** [comment]
This issue is solved now.
